### ISSUE TITLE
res undefined after updating webdriverio to 3.0.0

### ISSUE THREAD

**Issue by terekim** [webdriverio/webdrivercss#89]
I'm getting a `undefined: Cannot read property 'element' of undefined` error on the last assert line there after upgrading my webdriverio to 3.0.0. Code block works fine on webdriver 2.4.5. Is there a workaround for this? Thanks

```javascript
var webdriverio = require('webdriverio');
var options = {
    desiredCapabilities: {
        browserName: 'chrome'
    }
};
var browser = require('webdriverio').remote(options);

var webdrivercss = require('webdrivercss').init(browser, {
    screenshotRoot: 'webdrivercss-results/baseline',
    failedComparisonsRoot: 'webdrivercss-results/diffs',
    misMatchTolerance: 0.05,
    screenWidth: [1024]
});

describe('WebdriverCSS Test',function() {
  it('Test',function(done) {
    this.timeout(60000);
    browser
        .init()
        .url('http://localhost:9000/')
        .webdrivercss('test',[
            {
                name: 'element',
                elem: ['.class1', '.class2']
            }
        ], function(err,res) {
           assert.ok(res.element[0].isWithinMisMatchTolerance);
           done();
        })
        .end();
    });
});
```

**Comment by christian-bromann** [comment]
Hi @terekim , I am currently working on updating WebdriverCSS so it works with WebdriverIO `v3`. Currently it does not work. Please stay tuned.

**Comment by peter-mouland** [comment]
hey @christian-bromann , any update on this?

**Comment by zvictor** [comment]
Shouldn't this issue stay open while the community works on it?

**Comment by nickspiel** [comment]
I agree, this is still an issue so it should remain open.

@christian-bromann can you provide an update?

**Comment by bognix** [comment]
@christian-bromann is there any branch/fork where you work on it actively? I would like to help

**Comment by christian-bromann** [comment]
@bognix I am using master right now ¯\_(ツ)_/¯ .. if you like to help me find me on the Gitter channel and we can discuss everything. Thanks!
